# Generated by Django 5.0.1 on 2024-01-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailerMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Тема письма')),
                ('message', models.TextField(verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Mailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('time_start', models.DateField(verbose_name='Время начала')),
                ('time_stop', models.DateField(verbose_name='Время окончания')),
                ('frequency', models.CharField(choices=[('DAY', 'Каждый день'), ('WEEK', 'Каждую неделю'), ('MONTH', 'Каждый месяц')], max_length=100, verbose_name='Периодичность')),
                ('status', models.CharField(choices=[('DRAFT', 'черновик'), ('COMPLETE', 'Завершено'), ('CREATED', 'Создано'), ('LAUNCHED', 'Запущено')], max_length=100, verbose_name='Статус рассылки')),
                ('clients', models.ManyToManyField(related_name='mailers', to='client.client', verbose_name='Клиенты')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'ordering': ['id'],
            },
        ),
    ]
