# Generated by Django 4.2.7 on 2024-02-02 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0003_mailer_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailer',
            name='status',
            field=models.CharField(choices=[('COMPLETE', 'Завершено'), ('CREATED', 'Создано'), ('LAUNCHED', 'Запущено')], max_length=100, verbose_name='Статус рассылки'),
        ),
    ]
