# Generated by Django 4.2.7 on 2024-02-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0004_alter_mailer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailer',
            name='time_start',
            field=models.DateTimeField(verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='mailer',
            name='time_stop',
            field=models.DateTimeField(verbose_name='Время окончания'),
        ),
    ]
