# Generated by Django 4.2.7 on 2024-02-05 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mailer', '0007_mailermessage_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailer',
            name='owner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setting', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
    ]
