# Generated by Django 4.2.7 on 2024-02-05 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0008_mailer_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailer',
            options={'ordering': ['id'], 'permissions': (('view_mailer_list', 'Может просматривать список рассылок'), ('change_status', 'Может отключать рассылку')), 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
